---
# tasks file for nginx
- name: Install EPEL release for nginx
  yum: name=epel-release state=present

- name: Install nginx web server
  yum: name=nginx state=installed update_cache=true
  become: yes
- name: copy config
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  become: yes
- name: start nginx
  service:
    name: nginx
    state: started
  become: yes