---
# tasks file for nginx
- name: install nginx
  yum:
    name: nginx
    state: latest

- name: copy nginx config
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: start nginx
  service:
    name: nginx
    state: started
    enabled: yes
