- hosts: all
  pre_tasks:
  - name: Creating directory for facts
    file:
      path: /etc/ansible/facts.d
      state: directory
    become: yes
    become_user: root

  roles:
  - jenkins
  - nginx






