---
- name: save java details
  copy: 
    content: >
      {
        "version": "{{ nginx_version.stdout }}",
        "installed": "{{ ansible_date_time.iso8601 }}"
      }
    dest: /etc/ansible/facts.d/nginx.fact
  become: yes
